aws_region           = "eu-central-1"
telemetry_bucket     = "greenhouse-telemetry-bucket"
site_bucket          = "greenhouse-web-site"
db_username          = "postgres"
db_name              = "greenhouse"
ml_artifact_bucket   = "greenhouse-ml-artifacts"
ml_artifact_key      = "ml_service.zip"
