name: Terraform CD

on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-cd.yml'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region:            us-east-1

      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v3
      #   with:
      #     terraform_version: 1.8.5

      # - name: Terraform Init
      #   run: terraform init -input=false

      # - name: Terraform Validate
      #   run: terraform validate

      # - name: Terraform Plan
      #   run: terraform plan -input=false -var-file="envs/prod.tfvars" -out tfplan

      # - name: Terraform Apply
      #   if: github.event_name == 'push'
      #   run: terraform apply -input=false -auto-approve tfplan

      - name: No-op
        run: echo "Terraform CD steps are commented out; nothing to do."
