name: Terraform (LocalStack)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
        env:
          SERVICES: "s3,lambda,sts,iam,cloudwatch,logs,events,ec2,ecr,ecs,elbv2,cloudfront,rds,secretsmanager"
          DEBUG: "1"
        options: >-
          --health-cmd="awslocal s3 ls || exit 1"
          --health-interval=10s
          --health-retries=10
          --health-timeout=5s

    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
      AWS_ENDPOINT_URL: http://localhost:4566

    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Install build deps for ZIP
        run: |
          sudo apt-get update
          sudo apt-get install -y zip python3-pip
          python3 -m pip install --upgrade pip
          # (optional) install requirements to compile wheels in the ZIP; not strictly needed for building your zip

      - name: Build ML ZIP
        working-directory: ./mal
        run: bash scripts/build_zip.sh

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -reconfigure

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -var-file="envs/dev.tfvars"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ./terraform
        run: terraform apply -auto-approve -var-file="envs/dev.tfvars"
