name: Terraform Apply

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      # Inject real‐AWS bucket names & DB creds from GitHub Secrets
      TF_VAR_telemetry_bucket:   ${{ secrets.TELEMETRY_BUCKET }}
      TF_VAR_site_bucket:        ${{ secrets.SITE_BUCKET }}
      TF_VAR_db_username:        ${{ secrets.DB_USERNAME }}
      TF_VAR_db_name:            ${{ secrets.DB_NAME }}
      TF_VAR_ml_artifact_bucket: ${{ secrets.ML_BUCKET }}
      TF_VAR_ml_artifact_key:    "ml_service.zip"
      AWS_REGION:                eu-central-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
